### ISSUE TITLE
✨ [Feat] JPA 엔티티 생성

### ISSUE THREAD

**Issue by Eunjin3395** [Daily-Step/challenge-server#3]
## 📝 기능 개요

ERD 설계 바탕으로 JPA 엔티티 생성

## ✅ Todo
- [x] JPA 엔티티 생성
- [x] JPA 연관관계 매핑
- [x] createdAt, updatedAt 타임스탬프 자동으로 입력되도록 설정
