### ISSUE TITLE
✨ [Feat] 내 회원 정보 조회 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Daily-Step/challenge-server#33]
## 📝 기능 개요

내 회원 정보 조회 API 구현 및 테스트

## ✅ Todo
- [x] 내 회원 정보 조회 API 구현
- [x] 내 회원 정보 조회 API 서비스 테스트
- [x] 내 회원 정보 조회 API 컨트롤러 테스트
