### ISSUE TITLE
✨ [Feat] 닉네임 중복 확인 API 구현 및 테스트

### ISSUE THREAD

**Issue by Eunjin3395** [Daily-Step/challenge-server#34]
## 📝 기능 개요

닉네임 중복 확인 API 구현 및 테스트

## ✅ Todo
- [x] 닉네임 중복 확인 API 구현
- [x] 닉네임 중복 확인 API 서비스 테스트
- [x] 닉네임 중복 확인 API 컨트롤러 테스트
